### ISSUE TITLE
Choosing a new ruler when no people are availabe crashes the app

### ISSUE THREAD

**Issue by myxor** [myxor/WhoRules#11]
Exception:

`java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388)
        at de.marcoheiming.whorules.MainActivity.chooseNextRandomRuler(MainActivity.java:192)
        at de.marcoheiming.whorules.MainActivity$1$2.onClick(MainActivity.java:72)`

**Comment by myxor** [comment]
Fixed with https://github.com/myxor/WhoRules/commit/ac3eb861e10af0c98fcf6682f16437975f015340.
